# ----------------------------
# ConfigMap pour Spring Boot
# ----------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: devops
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/springdb?createDatabaseIfNotExist=true
  # Ajoutez d'autres variables si nécessaire
---
# ----------------------------
# Secret pour Spring Boot
# ----------------------------
apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: devops
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==       # root
  SPRING_DATASOURCE_PASSWORD: cm9vdDEyMw==   # root123
---
# ----------------------------
# Deployment Spring Boot
# ----------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: devops
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: oussemabh1/oussemabenelhaj_4twin2:build-65
          imagePullPolicy: Always
          ports:
            - containerPort: 8089         # corrigé pour match Spring Boot
          envFrom:
            - configMapRef:
                name: spring-config
            - secretRef:
                name: spring-secret
---
# ----------------------------
# Service NodePort pour Spring Boot
# ----------------------------
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
spec:
  selector:
    app: spring-app
  type: NodePort
  ports:
    - port: 8089
      targetPort: 8089        # corrigé pour match containerPort
      nodePort: 30091
